### ISSUE TITLE
Freeing emory through checker

### ISSUE THREAD

**Issue by AadhyaKocha** [France-ioi/taskgrader#104]
I am working on this [issue](https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/722) to add the ability to check for if memory is freed in the checker. 
We are hoping to duplicate something like [this](https://github.com/remisharrock/cspace/blob/5364927c1b07b8ffcabebceea22cc97ef1f200da/05%20C%20Programming%20Advanced%20Data%20Types/Unit%205.2%20Structures%20and%20pointers/02%20Allocate%20memory%20for%20structures/02_allocate%20memory%20for%20polygon%20structures/tests/gen/checker.py) checker which has a line on freeing into this [quiz](https://github.com/remisharrock/cspace/blob/5364927c1b07b8ffcabebceea22cc97ef1f200da/05%20C%20Programming%20Advanced%20Data%20Types/Unit%205.3%20Linked%20lists/04%20Free%20an%20entire%20linked%20list/01_free%20a%20linked%20list%20of%20students/tests/gen/checker.py) which is not doing the checking as seen in its python code.
However, we are not sure how to make this change and how to get it to update into the edX implementation. How does the python checked connect to Task Grader and to edX?

Here is a screenshot of another checker that checks for memory free correctly:
![Screenshot 2022-02-17 at 9 55 11 AM](https://user-images.githubusercontent.com/51734801/154507705-c8d83d6f-ae5a-4ba7-bc1f-9745a9175d7c.png)

**Comment by mblockelet** [comment]
Hi,

There seems to be an issue with the task editor which prevents from updating the checker, so I'll have a look into that.

I updated your checker manually in the meanwhile so that it includes the code from the other checker which was linked and had the check for "free" usage.

I'm not sure I understand the question about how the checker "connects" ; the checker is executed by the taskgrader to determine the grade.

**Comment by AadhyaKocha** [comment]
Looks like it is checking freeing memory correctly now. Thank you!
