### ISSUE TITLE
Task grader feedback

### ISSUE THREAD

**Issue by AadhyaKocha** [France-ioi/taskgrader#107]
To respond to student input, I switch on these two settings for feedback:
<img width="1053" alt="Screenshot 2022-04-14 at 9 42 36 AM" src="https://user-images.githubusercontent.com/51734801/163509110-67fdc09f-5310-43a3-957c-57b3081805a4.png">

The partial feedback creates the tag for "must be a string" and "you didn't answer the question" which is what we want. The detailed feedback shows after submitting when the user presses "show answer" in this case saying "Think hard!"
<img width="1390" alt="Screenshot 2022-04-14 at 10 35 54 PM" src="https://user-images.githubusercontent.com/51734801/163509059-d52327de-a7b3-4ba8-8495-ac7999f6ecac.png">
<img width="1357" alt="Screenshot 2022-04-14 at 10 38 23 PM" src="https://user-images.githubusercontent.com/51734801/163509314-5c300a31-1b10-40a2-9ccf-4f9adc46c5df.png">

In the detailed feedback we don't want to provide the answer but make it act kind of like a hint. 
Q1. Can the wording of "show answer" be changed to "show hint"?
Q2. Does switching on these 2 feedback features mess anything in the backend? Wondering because other we will go through Mooc 1-7 and switch these options on for every quiz especially the partial feedback setting.

**Comment by mblockelet** [comment]
Hi @AadhyaKocha,

Q1. We could make a system so the wording could be changed, I'll think about it and come back to you with a solution by the middle of next week, as I'm not sure what I'm thinking of would be good.
Q2. No it doesn't change anything in the backend, those options are mostly managed by the frontend. If the behavior is what you would like to have, then you can use it this way. Just be completely sure the behavior is what you expect before changing them all :)

**Comment by AadhyaKocha** [comment]
Thank you @mblockelet! Any updates on Q1? 
We are trying to use this feedback option for this [quiz](https://github.com/France-ioi/taskgrader/issues/106) as well so need to know how the answer can show for one option

**Comment by mblockelet** [comment]
Hi @AadhyaKocha, I'm really sorry for the delay.

I added the option as a "sub-language" so that it'll be easier to make such changes in the future.

To change the button to "Show hint", you now need to use the option "Sub-language for various texts" which you should see in the Task editor now, and write `hint` as value for that option.

Please try it and tell me if that works as you want.

**Comment by remisharrock** [comment]
I'm going back to issue  https://github.com/France-ioi/taskgrader/issues/106 
code here : 
https://github.com/remisharrock/cspace/tree/master/05%20C%20Programming%20Advanced%20Data%20Types/Unit%205.3%20Linked%20lists/02%20Linking%20nodes/02_createStudent%20need%20help
we need it to work like this:
- if the student chooses "I found the solution by myself ... " the student GETS the points and CANNOT access the solution
- if the student chooses "I would like to get the code ..." the student DO NOT GET the points and CAN access the solution
we don't know if it possible to do it and how ? 
Thanks for you help @mblockelet

**Comment by mblockelet** [comment]
Hi @remisharrock ,

I must have missed the second question in the issue #106, sorry for that.

Currently, you could do so by using a "Question with input" and setting the "correct answer" to a JS function which returns an object `{score: 1}` or `{score: 0, message: "<pre>the secret program</pre>"}` depending on the answer given.

It is inconvenient as you need to set it as a "free input" question, but you always can use a regexp such as `^(yes|no)$` on the question.

For simplicity of use, the choice questions don't support it easily through the task editor.

**Comment by remisharrock** [comment]
that's an idea, we will try, @AadhyaKocha could you try that :
free input question + adding an explanation to answer "yes" or "no" and a small JavaScript code ? ;) 
I might help you there !

**Comment by AadhyaKocha** [comment]
Yes! Thank you so much. I will try this now and keep you both posted

**Comment by mblockelet** [comment]
Hi @AadhyaKocha ,

1. When testing directly, outside of the course platform, the default "bad answer" score is -3, which is why it displays that. It's just how our tasks work when not integrated in a platform, and also why the maximum score as shown is 40. Your question is configured properly, don't worry!
2. I tried it and it worked for me, maybe there were a mistake somewhere? Note that you need to put the "Answer input format" to "regexp" for the regexp to be used.
3. I added a new field that you will see in the bottom of the task-editor, called "Custom CSS". If you put there `.freeze-overlay { display: none !important; }`, it will allow users to select the code. I made this field to try to catch more easily various possibilities in the future.

Note that for 2 and 3 I modified the task linked directly so that you don't have to do it. Tell me if that solves all issues!

Cheers!

**Comment by AadhyaKocha** [comment]
Thank you!
