### ISSUE TITLE
Problem with quizzes

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/taskgrader#108]
Hi Michel, 
I am not sure I am on the correct repo. This issue is about quizzes. 
Here is the detail. https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/762 
We have observed that several learners get confused on edX. 
Can we do something about it? 
Thanks much

**Comment by mblockelet** [comment]
Hi Ella,

I changed the display of the little "restart" popup to always display right above the normal line with the "Submit" and the "Restart" buttons, this way it should always be visible.

This was due to issues when the quiz is integrated in an iframe, as is happening on edX for instance, as the popup would display in the middle of the "screen", but the notion of "screen" is different in an iframe and it would hence display in the middle of the iframe.

Please tell me if that change introduces issues sometimes, but I think overall it should be better.
