### ISSUE TITLE
A quiz shows an error 

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/taskgrader#109]
Hi Michel, 

Here is an error we have experimented https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/758

Thanks for your help, 

Best, 

Ella

**Comment by mblockelet** [comment]
Hi @EllaHa ,

The error should be fixed now. The issue was that the link configured in Coursera was wrong (by a digit), the `content_id` configured in the link didn't correspond to the correct one because it had an extra "1" at the end.

The process now works for me (I get my grade recorded on Coursera), please tell me if you encounter again the issue on another task, and the `content_id` is right.
