### ISSUE TITLE
Quiz aesthetic

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/taskgrader#111]
Hi Michel, 
We might need your help on his one: 
https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/750

Any suggestion to avoid this problem? 

Best,

**Comment by mblockelet** [comment]
Hi Ella,

I fixed the first task mentioned in that bugreport (I wasn't sure what would be the preferred solution for the second one).

The issue was that a lot of spaces had been put in the answer (which was longer than the others) at the end of the lines, probably a bad copy-paste from a terminal?

If there are other spaces issues on other tasks, you can fix them by simply removing the spaces at the end of the lines for each possible answer.
