### ISSUE TITLE
Il n'existe pas de tests pour ce problème.

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#13]
après importation, avec le checker par défaut, j'ai toujours ce message:
Il n'existe pas de tests pour ce problème.

**Comment by eroux** [comment]
en fait je ne comprend pas : quelles actions est-ce que je peux faire pour reproduire le problème exactement ? où est affiché ce message, dans quel contexte ?

**Comment by eroux** [comment]
ah ok je vois, je regarde

**Comment by eroux** [comment]
En fait taskgrader renvoie à taskplatform le json suivant:

```json
{"errorcode":1,"errormsg":"Error while regenerating defaultParams for task `$ROOT_PATH\/Telecom\/MOOC1\/Week2\/taskTemplate`, exitcode=1.\nFatal taskgrader error.\nstdout:\n\nstderr:\nTraceback (most recent call last):\n  File \"\/home\/grader\/tasks\/v01\/_common\/taskgrader\/taskgrader.py\", line 1730, in <module>\n    json.dump(evaluation(inJson), sys.stdout)\n  File \"\/home\/grader\/tasks\/v01\/_common\/taskgrader\/taskgrader.py\", line 1393, in evaluation\n    raise Exception(\"Task path `%s` invalid (folder not found).\" % evaluationParams['taskPath'])\nException: Task path `\/home\/grader\/tasks\/v01\/\/Telecom\/MOOC1\/Week2\/taskTemplate` invalid (folder not found).\n"}
```

@mblockelet est-ce que tu vois d'où ça vient ?

**Comment by remisharrock** [comment]
Error while regenerating defaultParams  ;  ça veut dire qu'il ne faut pas envoyer defaultParams.json  sur le SVN peut-être ?

**Comment by remisharrock** [comment]
sinon on dirait aussi que ya deux  /  
\/home\/grader\/tasks\/v01\/\/Telecom\/MOOC1\/Week2\/taskTemplate
entre v01 et Telecom

**Comment by remisharrock** [comment]
ça refonctionne qu'est-ce qui a changé ?

**Comment by mblockelet** [comment]
Salut, c'était encore une erreur avec SVN qui, lorsque le serveur lui demandait de mettre à jour le chemin, il renvoyait un message "Skipped path" mais pas d'erreur...
Je vais chercher une façon de s'assurer un peu mieux que le dossier est bien récupéré du SVN...
(En attendant j'ai mis à jour à la main donc ça devrait être bon !)

**Comment by remisharrock** [comment]
@mblockelet @mathias-hiron  je pense que ça vient peut être de extra dirs ,  tu vois ce que je veux "dir" hehe ?

**Comment by remisharrock** [comment]
@mblockelet j'ai pas mal de tasks à importer cet après-midi pour le MOOC semaine 2 , est-ce que l'automatisation de l'import fonctionne ou faut repasser à la main pour chaque import ?

**Comment by eroux** [comment]
ce n'est pas lié à l'import, le taskgrader a sa propre version du svn qu'il doit mettre à jour, indépendamment

**Comment by mblockelet** [comment]
L'import sur svnimport devrait fonctionner sans problème (le problème actuel ne l'affecte pas); côté évaluation, si la tâche est déjà dans le svn en ce moment, c'est bon, et pour les tâches ajoutées à l'avenir dans le SVN, je suis en train de tenter d'ajouter des "sécurités" pour s'assurer que le SVN récupère bien les nouvelles versions sans "skipped" ou autres... (J'espère que d'ici une heure ce sera bon...!)

**Comment by mblockelet** [comment]
Fixed by France-ioi/graderqueue@b3fd2e2ed78b078632c750a4992db37f746d360d .

En principe c'est corrigé. En fait, SVN a un comportement assez paresseux et embêtant; l'erreur pouvait être reproduite ainsi :

* on part d'un dossier vide dans SVN
* on crée `dossier/` et `dossier/task/` dans le même commit
* on fait `svn up dossier/task/` sur un autre serveur qui n'a pas ce commit
* SVN va tout simplement ignorer la commande, considérant que si `dossier/` n'existe pas, alors il ne va pas s'embêter à essayer de mettre à jour `dossier/task/`

Du coup il l'ignore juste (même si c'est le dossier explicitement donné en ligne de commande), et ne renvoie pas de code d'erreur. Bref, maintenant l'update se fait sur le premier dossier parent qui existe, comme ça le SVN update fonctionne...

Merci d'avoir signalé l'erreur ! J'espère que maintenant ce sera bon.
