### ISSUE TITLE
whitespace character ?

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#76]
could you check why many learners have this error ? 
![image](https://user-images.githubusercontent.com/8048877/84883030-5d944a00-b090-11ea-9091-1f8e315e38a2.png)
Here is the link to the forum, we still have to answer to why this is happening.
https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/642
To get the codes of the learners that have the error in the forums, look at the login of the learner in the forum:

![image](https://user-images.githubusercontent.com/8048877/84883373-b95ed300-b090-11ea-8229-d1ffe2c2ea24.png)

then download the anonymized id here:

![image](https://user-images.githubusercontent.com/8048877/84883302-a6e49980-b090-11ea-990d-70ac80e8236b.png)

and link it to the username the can be found here :
![image](https://user-images.githubusercontent.com/8048877/84883487-db585580-b090-11ea-8634-66314390caae.png)

thanks for your help

**Comment by mblockelet** [comment]
Hello,

For the "whitespace" character, there is (in general) no actual character there in the student's solution output, it is just the indication that there is something missing there. It was put because without that, a lot of students were confused as to what was the mistake, so we highlight the fact that there is nothing there.

For the user issue, as others have said in that thread, it is that some variables were not initialized properly.
