### ISSUE TITLE
This submission is being evaluated" for a while only for it to later say that "There are no tests for this task." 

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#78]
Here are the details, thanks for your help

https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.05+1T2020/discussion/forum/a3085ebce728064ce1994ce9c0fb2df00ca84311/threads/5f6257e026ea960a69fdc3fb

**Comment by mblockelet** [comment]
Hello, the "Activity: manipulate structures with functions" checker is doing an infinite loop (or at least, executing for minutes without ending). which is why the user gets the message "There are no tests for this task." as we end up with no checker output at all.

When I try executing the checker manually, each time after a minute when I interrupt it, it was executing line 367, if that helps.

**Comment by remisharrock** [comment]
Thanks for investigating:
is it this checker ? https://github.com/remisharrock/cspace/blob/master/05%20C%20Programming%20Advanced%20Data%20Types/Unit%205.1%20Structures/04%20Work%20with%20structures/manipulate%20structures%20with%20functions/tests/gen/checker.py 
If so we need to contact @Eli-Boardman  ?

**Comment by mblockelet** [comment]
Yes it's this one!
