### ISSUE TITLE
revert the changes for this quizz ? 

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#84]
Hello michel, I think something wrong happened with this commit 
https://github.com/remisharrock/cspace/commit/da2f261b430fa9288bce122d290c932985e663db 
can you see it ?

**Comment by mblockelet** [comment]
I reverted the changes, by editing through the task-editor so I could test whether it was an issue with the task-editor which caused that.

It seems the questions were changed to the type "question with single choice" instead of "question with input", do you know if it is an user mistake or an issue with the task-editor? I tested and don't seem to be reproducing the error with the task-editor, please tell me if it happens again.

Closes #83.

**Comment by remisharrock** [comment]
thank you, looks like I don't have any points with the correct answers:
![image](https://user-images.githubusercontent.com/8048877/98983280-d6ed7700-2520-11eb-9d0e-a83c9155b143.png)

**Comment by mblockelet** [comment]
Sorry, that's fixed now, it was just me not reimporting the task properly...
