### ISSUE TITLE
Default source file bug

### ISSUE THREAD

**Issue by AadhyaKocha** [France-ioi/taskgrader#98]
@mblockelet 

As described in this [error](https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/689), the default code in the solutions isn't showing up like most of our other quizzes. When I went to add a default source code in [Taskgrader](https://task-editor.france-ioi.org/#edit/cspace%2F05%20C%20Programming%20Advanced%20Data%20Types%2FUnit%205.1%20Structures%2F03%20Pass%20structures%20to%20functions%2F01_pass%20structures%20to%20functions), I noticed that there was a file earlier but it just isn't showing up anymore. This is because the default source input area has a delete option and is weirdly formatted (as if there was a file attached but isn't reading anymore). I have attached a screenshot of this on Taskgrader.
<img width="987" alt="Screenshot 2021-04-29 at 12 25 44 PM" src="https://user-images.githubusercontent.com/51734801/116586142-2238ed80-a8e7-11eb-90ac-3febf485d2cd.png">

Should I try deleting the existing file and adding a new source code file or is this a bug you could fix so I don't break anything?

**Comment by mblockelet** [comment]
Hello @AadhyaKocha !

This happened because the original file containing the source code (given.c) disappeared at some point. I cannot find it in the history of the cspace repository, so it's likely it was lost much before that repository was created.

It's safe to delete the bogus entry and add the defaultSource again.

If you encounter a buggy line such as the on in this screenshot, it means that task-editor couldn't find the file anymore, so it's likely there is an issue with the files somewhere. I'd recommend in that case to look at the repository to see if the original file can be located.

I will try to fix the display at some point!

**Comment by AadhyaKocha** [comment]
Great, thank you!

**Comment by AadhyaKocha** [comment]
Hi @mblockelet! Turns out, this issue is happening in all the courses in MOOC 5. I can go in and manually add all default test codes again but if there is a possible solution to prevent other MOOCs from behaving this way in the future? That would be great!
